Added cli
Thepigcat76/vm pull request #2
Opened 2024-08-08 18:21 UTC by Cr0a3

Hi,
I added cli options.
The help message:
![image](https://github.com/user-attachments/assets/c20c862b-601c-47a5-8a4b-0dcc2ecd45b6)
The version message:
![image](https://github.com/user-attachments/assets/2464648b-a4a8-4593-b1ce-69e00f699f66)

I also fixed a possible segfault when passing in unknown files.
I also  added a dump method wich dumps all of the register values and names.
Bye

2024-08-08 21:11 UTC, Thepigcat76 commented
Thanks for your pull request! Didn't expect any interaction on this project since it was just for fun but I appreciate it nonetheless. I reviewed your changes and overall they are really good! Just some minor things that I feel should be changed.

2024-08-08 21:16 UTC, Thepigcat76 requested changes

2024-08-08 21:16 UTC, Thepigcat76 commented on src/asm/runner.c
> +        printf("mov");
Is this print for debugging? If so, please remove it

2024-08-08 21:16 UTC, Thepigcat76 commented on src/cli.h
> +#ifndef CLI_H
please change header guards to use `#pragma once` instead of defines

2024-08-08 21:16 UTC, Thepigcat76 commented on src/vm/vm.c
> +#include "asm/ast.h"
maybe move the reg_to_string(...) function to vm.c so the asm parsing stuff and actual virtual machine stay seperate

2024-08-08 21:16 UTC, Thepigcat76 commented on src/asm/ast.h
> +char* reg_to_string(int num);
As i said, consider moving this to vm.c and possibly even making it static

2024-08-08 21:16 UTC, Thepigcat76 commented on src/vm/vm.h
> +void dump(VirtualMachine vm);
Consider passing the VirtualMachine as a pointer

2024-08-09 12:32 UTC, Cr0a3 commented
@Thepigcat76 fixed it

2024-08-09 16:52 UTC, Thepigcat76 commented on src/vm/vm.h
> +static char* reg_to_string(int num);
Static functions are essentially private, so there is no use in exposing them through a header file. Could you please remove this?

2024-08-09 16:53 UTC, Thepigcat76 commented
Thank you very much! Only one minor nitpick and then this can be merged :+1:

2024-08-09 17:10 UTC, Cr0a3 commented
> Only one minor nitpick and then this can be merged 👍

Which one?

2024-08-09 17:11 UTC, Cr0a3 commented
> Only one minor nitpick

Which one?

2024-08-09 17:24 UTC, Thepigcat76 commented
![image](https://github.com/user-attachments/assets/8b879e28-f0b7-4f24-8812-2bea123681fc)
This one, above my message

2024-08-09 17:34 UTC, Cr0a3 commented
Sorry fixed it

2024-08-09 21:50 UTC, Thepigcat76 approved these changes

2024-08-09 21:50 UTC, Thepigcat76 commented on src/vm/vm.h
> +static char* reg_to_string(int num);
Static functions are essentially private, so there is no use in exposing them through a header file. Could you please remove this?

2024-08-09 21:53 UTC, Thepigcat76 commented
No need to apologize, you did an amazing job with this pr! And btw, you have my biggest respect for being this young and still having this much knowledge :+1:

2024-08-09 21:53 UTC, merged

2024-08-10 05:01 UTC, Cr0a3 commented
Thank you very much